Module4 task2
htmlacademy-adaptive/1826213-mishka-24 pull request #6
Opened 2021-12-12 12:02 UTC by Denysmogyliuk

2021-12-16 00:02 UTC, vladpovelitsa requested changes
Есть парочка незначительных замечаний, в целом всё хорошо, ты молодец!

2021-12-16 00:02 UTC, vladpovelitsa commented on source/less/components/catalog.less
> +  }
указываешь флекс, а используешь свойства гридов

2021-12-16 00:02 UTC, vladpovelitsa commented on source/less/components/catalog.less
>  }
вроде ж решили отказаться от миксинов

2021-12-16 07:15 UTC, Denysmogyliuk commented on source/less/components/catalog.less
> +  }
Осталось от первоначальной версии на гридах)

2021-12-17 09:13 UTC, vladpovelitsa approved these changes
Всё ок, супер!

2021-12-17 09:13 UTC, merged